spring:
  application:
    name: tlgp-user-service
  profiles:
    active: dev
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

  cloud:
    nacos:
      config:
        server-addr: 8.162.4.221:8848 # Nacos 配置中心地址
        file-extension: yaml
        namespace: public # 指定为 dev 命名空间的 ID
      discovery:
        server-addr: 8.162.4.221:8848 # Nacos 注册中心地址
        namespace: public # 注册中心也可以使用命名空间隔离
  # (可选) 如果你想在本地测试数据库连接，可以在这里配置
#datasource:
#  url: jdbc:mysql://localhost:3306/tlgp-user?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#  username: root
#  password: mysql
#  driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082 # Use a different port
