server:
  port: 8081
spring:
  application:
    name: tlgp-order-service
  profiles:
    active: dev # 激活 dev 环境
  config:
    import:
#      - nacos:tlgp2-service.yaml # 从 Nacos 加载配置
        - optional:nacos:application-${spring.profiles.active}.yml  # 加载 application-dev.yml (公共配置)
        - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml # 加载 tlgp2-service-dev.yml (服务特定配置)

  cloud:
    nacos:
      config:
        server-addr: nacos:8848 # Nacos 配置中心地址
        file-extension: yaml
        namespace: public # 指定为 dev 命名空间的 ID
      discovery:
        server-addr: nacos:8848 # Nacos 注册中心地址
        namespace: public # 注册中心也可以使用命名空间隔离


# 添加 JWT 配置
#app:
#  jwt:
#    secret: "WW91clZlcnlTZWNyZXRLZXlGb3JKV1RHZW5lcmF0aW9uQW5kVmVyaWZpY2F0aW9u" # 替换为你的实际密钥
#    # 或者使用 base64 编码的密钥
#    # secret: "WW91clZlcnlTZWNyZXRLZXlGb3JKV1RHZW5lcmF0aW9uQW5kVmVyaWZpY2F0aW9u" # 示例，实际使用时请生成一个安全的密钥并编码
#    access-token-expiration: 86400000  # 1 day in milliseconds
#    refresh-token-expiration: 604800000 # 7 days in milliseconds
